language: R
dist: bionic
cache: packages

env:
  - INSTALL_TOOLS=true
  - INSTALL_TOOLS=false

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/mhcnuggetsr
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/epitope-prediction

before_script:
  - sudo apt install python3-pip
  - if [[ "$INSTALL_TOOLS" == true ]]; then Rscript -e 'mhcnuggetsr::install_mhcnuggets()'; fi
  - if [[ "$INSTALL_TOOLS" == true ]]; then Rscript -e 'pureseqtmr::install_pureseqtm()'; fi

after_failure:
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'

