
language: R
# dist: bionic # Uncomment until fix of https://travis-ci.community/t/r-install-broken-travis-ci-rstudio-org-returns-403/9640
cache: packages

env:
  - INSTALL_TOOLS=true
  - INSTALL_TOOLS=false

r_packages:
  - devtools
  - rgl

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - richelbilderbeek/babette
  - richelbilderbeek/tiebeaur
  - ropensci/spelling
  - ropensci/mcbette
  - thijsjanzen/nodeSub
  - richelbilderbeek/pirouette
  - richelbilderbeek/peregrine
  - richelbilderbeek/mhcnuggetsr
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/tmhmm
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/epitope-prediction
  - richelbilderbeek/epiprepreds
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/nmhc2ppreds

bioc_packages:
  - msa
  - bios2mds

before_install:
  # Rmpfr
  - sudo apt install -qq libmpfr-dev
  # ImageMagick
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  # Fix rJava error, from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
  - sudo $(which R) CMD javareconf
  # bios2mds
  - sudo apt-get install libglu1-mesa-dev
 

before_script:
  # Install rJava, then ...
  - sudo apt install -qq r-cran-rjava
  # from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/4
  - sudo R CMD javareconf
  - if [[ "$INSTALL_TOOLS" == true ]]; then sudo apt install tcsh; fi
  - if [[ "$INSTALL_TOOLS" == true ]]; then Rscript -e 'mhcnuggetsr::install_mhcnuggets()'; fi
  - if [[ "$INSTALL_TOOLS" == true ]]; then Rscript -e 'pureseqtmr::install_pureseqtm()'; fi
  - if [[ "$INSTALL_TOOLS" == true ]]; then Rscript -e 'if (netmhc2pan::is_url_valid()) netmhc2pan::install_netmhc2pan()'; fi

after_failure:
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

