language: r
cache: packages

os:
  - osx

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/epitopeome
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/tmhmm
  - MangoTheCat/goodpractice

before_script:
  - # wget ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/QfO/Bacteria/UP000001584_83332.fasta.gz
  - # gunzip UP000001584_83332.fasta.gz
  - # rm UP000001584_83332.fasta.gz

script:
  - travis_wait 50 R CMD build .
  - travis_wait 50 R CMD check *tar.gz

after_script:
  - qmake
  - make

after_success:
  - ls
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'

after_failure:
  - ls
