language: R
dist: bionic
cache: packages

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/tmhmm
  - richelbilderbeek/epitopeome
  - richelbilderbeek/beastier
  - jtextor/epitope-prediction

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -qq libmagick++-dev
  # Boost
  - sudo apt-get install -qq libboost-all-dev
  # SSL
  - sudo apt-get install -qq libssl-dev

before_script:
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  ## Install and test TMHMM
  #- Rscript -e "tmhmm::install_tmhmm()"
  #- echo -e ">sp|L0T550|RIP2_MYCTU_158_180\nAVLWAGVAFLAFLQLTALVLNLL" > example.fasta
  #- |
  #  ~/.local/share/tmhmm-2.0c/bin/decodeanhmm.Linux_x86_64 \
  #  ~/.local/share/tmhmm-2.0c/lib/TMHMM2.0.model \
  #  example.fasta \
  #  -f ~/.local/share/tmhmm-2.0c/lib/TMHMM2.0.options || true
  #- rm example.fasta
  ## Install and test NetMHC2pan
  #- sudo apt install tcsh
  #- Rscript -e "netmhc2pan::install_netmhc2pan()"
  #- echo -e ">sp|L0T550|RIP2_MYCTU_158_180\nAVLWAGVAFLAFLQLTALVLNLL" > example.fasta
  #- ~/.local/share/netMHCIIpan-3.2/netMHCIIpan -f example.fasta
  #- rm example.fasta

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'

after_failure:
  - pwd
  - find . | egrep "fasta"
