language: R
dist: bionic
cache: packages

env:
  - INSTALL_MHCNUGGETS=true
  - INSTALL_MHCNUGGETS=false

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/mhcnuggetsr
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/epitope-prediction

before_install:
  # Boost
  - sudo apt-get install -qq libboost-all-dev

before_script:
  - sudo apt install python3-pip
  - if [[ "$INSTALL_MHCNUGGETS" == true ]]; then Rscript -e 'mhcnuggetsr::install_mhcnuggets()'; fi

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'

after_failure:
  - pwd
  - find . | egrep "fasta"
