language: R
# dist: bionic # Uncomment until fix of https://travis-ci.community/t/r-install-broken-travis-ci-rstudio-org-returns-403/9640
cache: packages

env:
  - INSTALL_TOOLS=true
  - INSTALL_TOOLS=false

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/mhcnuggetsr
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/epitope-prediction
  - richelbilderbeek/epiprepreds
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/nmhc2ppreds

before_script:
  - if [[ "$INSTALL_TOOLS" == true ]]; then sudo apt install tcsh; fi
  - if [[ "$INSTALL_TOOLS" == true ]]; then Rscript -e 'mhcnuggetsr::install_mhcnuggets()'; fi
  - if [[ "$INSTALL_TOOLS" == true ]]; then Rscript -e 'pureseqtmr::install_pureseqtm()'; fi
  - if [[ "$INSTALL_TOOLS" == true ]]; then Rscript -e 'netmhc2pan::install_netmhc2pan()'; fi

after_failure:
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'

