language: R
cache: packages
dist: trusty

r_packages:
  - devtools
  - git2r

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/epitopeome
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/tmhmm
  - MangoTheCat/goodpractice

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  - sudo apt-get install -y libgit2-dev
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

before_script:
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # Boost
  - sudo apt-get install libboost-all-dev
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Install TMHMM
  - Rscript -e "tmhmm::install_tmhmm(tmhmm::get_tmhmm_url())"
  # Install NetMHC2pan
  - which tcsh
  - Rscript -e "netmhc2pan::install_netmhc2pan(netmhc2pan::get_netmhc2pan_url())"
  # proselint
  - sudo pip install proselint

after_script:
  - qmake
  - make

after_success:
  - ls
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'

after_failure:
  - ls
  - apt-cache search libgit2
