// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// create_tmh_fasta_cpp
void create_tmh_fasta_cpp(const std::string& proteome_filename, const std::string& tmhs_filename, const std::string& tmh_fasta_filename);
RcppExport SEXP _bbbq_create_tmh_fasta_cpp(SEXP proteome_filenameSEXP, SEXP tmhs_filenameSEXP, SEXP tmh_fasta_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type proteome_filename(proteome_filenameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type tmhs_filename(tmhs_filenameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type tmh_fasta_filename(tmh_fasta_filenameSEXP);
    create_tmh_fasta_cpp(proteome_filename, tmhs_filename, tmh_fasta_filename);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bbbq_create_tmh_fasta_cpp", (DL_FUNC) &_bbbq_create_tmh_fasta_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_bbbq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
