#' This function does nothing. It is intended to inherit is parameters'
#' documentation.
#' @param binding_strength_threshold threshold of the MHC2 allele's
#'   binding strength. A low threshold, e.g. \code{5.0}, selects for the top
#'   5 percent best binders
#' @param epitopeome_filename name of the file to store the epitopeome
#'   output.
#'   By default, this filename is generated by \link{tempfile},
#'   and will be put in the \code{/tmp} folder,
#'   which is cleaned by the operating system
#' @param fasta_filename name of a FASTA file
#' @param haplotype one MHC-I or MHC-II haplotype
#' @param haplotypes a list of MHC-I or MHC-II haplotypes
#' @param hydrophobe_control_peptides_as_data_filename
#'   filename that stores hydrophobe control peptides
#'   as R data,
#'   for example `work/hydrophobe-control-peptides.Rdata`
#' @param ic50_threshold peptides with a predicted IC50 value (in nM)
#'   lower than this will be considered binders.
#'   A threshold of 500 (nM) is common.
#' @param kyte_doolittle_scale_as_data_filename
#'   filename that stores the Kyte-Doolittle scale of
#'   hydrophobicity,
#'   for example `data/kyte.doolittle.scale.Rdata`
#' @param max_hydrophobicity the maximal hydrophobicity
#' @param mhc_haplotype haplotype of either HMC-I or MHC-II.
#'   Use \link{get_mhc1_haplotypes} to get a list of all MHC-I haplotypes.
#'   Use \link{get_mhc2_haplotypes} to get a list of all MHC-II haplotypes.
#' @param mhc_1_haplotype HMC-I haplotope.
#'   Use \link{get_mhc1_haplotypes} to get a list of all haplotypes
#' @param mhc_2_haplotype HMC-II haplotope.
#'   Use \link{get_mhc2_haplotypes} to get a list of all haplotypes
#' @param min_hydrophobicity the minimal hydrophobicity
#' @param n_peptides number of peptides
#' @param non_tmh_eluted_filename
#'   Filename for the non-TMHs found on B-cells,
#'   for example `data/non-TMH-Bcell-elution.txt`
#' @param peptide peptide sequence, for example,
#' \code{ARNDCQEV}
#' @param peptides one ore more peptide sequences
#' @param peptide_length length of the peptide in amino acids
#' @param percentile how low the IC50 must be for the protein to
#'   be considered a binder. For example, 0.02 denotes that the protein
#'   must have an IC50 in the lowest 2 percent range.
#'   The default value is returned by \link{get_ic50_percentile_binder}.
#' @param png_filename name of a PNG file
#' @param protein_lengths_filename filename to store the
#'   length of all proteins in proteome,
#'   for example `work/protein-lengths.txt`
#' @param protein_sequence a protein sequence
#' @param protein_sequences one or more protein sequences
#' @param proteome_as_data_filename filename to store the
#'   proteome in R data format,
#'   for example `work/proteome.Rdata`
#' @param proteome_9mer_hydrophobicity_as_data_filename
#'   filename to store the
#'   proteome 9-mer hydrophobicities in R data format,
#'   for example `work/proteome.9mer.hydrophobicity.Rdata`
#' @param proteome_filename name of the file the proteome will be stored at
#' @param target_name name of organism or virus or testing
#'  dataset.
#' @param tmh_9mers_as_data_filename filename to store
#'   per TMH protein, the indices at which it is TMH,
#'   in R data format.
#'   for example `work/tmh.9mers.Rdata`
#' @param tmh_eluted_filename
#'   Filename for the TMHs found on B-cells,
#'   for example, `data/TMH-Bcell-elution.txt`
#' @param tmh_overlapping_binders_as_data_filename filename to store
#'   per TMH overlapping binders
#'   in R data format.
#'   for example `work/tmh-overlapping-binders.Rdata`
#' @param pureseqtmr_filename name of the file to store the
#'   PureseqTM output.
#'   By default, this filename is generated by \link{tempfile},
#'   and will be put in the \code{/tmp} folder,
#'   which is cleaned by the operating system
#' \code{mhcn} for \link[mhcnuggetsr]{mhcnuggetsr}
#' @param topology a topology,
#'   as created by \link[pureseqtmr]{predict_topology}
#' @param trans_membrane_analysis_filename Filename for
#'   uhhh, something, for example
#'   `tmh-predictions/trans-membrane-analysis-shortened.txt`
#' @param triplet a DNA triplet
#' @param verbose set to TRUE for more output
#' @author Richèl J.C. Bilderbeek
#' @note This is an internal function, so it should be marked with
#'   \code{@noRd}. This is not done, as this will disallow all
#'   functions to find the documentation parameters
default_params_doc <- function(
  binding_strength_threshold,
  epitopeome_filename,
  fasta_filename,
  haplotype,
  haplotypes,
  hydrophobe_control_peptides_as_data_filename,
  ic50_threshold,
  kyte_doolittle_scale_as_data_filename,
  max_hydrophobicity,
  mhc_haplotype,
  mhc_1_haplotype,
  mhc_2_haplotype,
  min_hydrophobicity,
  n_peptides,
  non_tmh_eluted_filename,
  peptide,
  peptides,
  peptide_length,
  percentile,
  png_filename,
  protein_lengths_filename,
  protein_sequence,
  protein_sequences,
  proteome_filename,
  proteome_as_data_filename,
  proteome_9mer_hydrophobicity_as_data_filename,
  target_name,
  tmh_9mers_as_data_filename,
  tmh_eluted_filename,
  tmh_overlapping_binders_as_data_filename,
  pureseqtmr_filename,
  topology,
  trans_membrane_analysis_filename,
  triplet,
  verbose
) {
  # Nothing
}
