#' This function does nothing. It is intended to inherit is parameters'
#' documentation.
#' @param alleles one or more alleles, e.g. \code{DRB1_0101}.
#'   See \link[netmhc2pan]{get_netmhc2pan_alleles} for a full list
#' @param binding_strength_threshold threshold of the MHC2 allele's
#'   binding strength. A low threshold, e.g. \code{5.0}, selects for the top
#'   5 percent best binders
#' @param epitopeome_filename name of the file to store the epitopeome
#'   output.
#'   By default, this filename is generated by \link{tempfile},
#'   and will be put in the \code{/tmp} folder,
#'   which is cleaned by the operating system
#' @param fasta_filename name of a FASTA file
#' @param haplotypes a list of MHC-I or MHC-II haplotypes
#' @param kyte_doolittle_scale_as_data_filename
#'   filename that stores the Kyte-Doolittle scale of
#'   hydrophobicity,
#'   for example `data/kyte.doolittle.scale.Rdata`
#' @param netmhc2pan_filename name of the file to store the
#'   NetMHC2pan output.
#'   By default, this filename is generated by \link{tempfile},
#'   and will be put in the \code{/tmp} folder,
#'   which is cleaned by the operating system
#' @param protein_lengths_filename filename to store the
#'   length of all proteins in proteome,
#'   for example `work/protein-lengths.txt`
#' @param proteome_filename name of the file the proteome will be stored at
#' @param tmh_9mers_as_data_filename filename to store
#'   per TMH protein, the indices at which it is TMH,
#'   in R data format.
#'   for example `work/tmh.9mers.Rdata`
#' @param tmh_overlapping_binders_as_data_filename filename to store
#'   per TMH overlapping binders
#'   in R data format.
#'   for example `work/tmh-overlapping-binders.Rdata`
#' @param tmhmm_filename name of the file to store the
#'   TMHMM output.
#'   By default, this filename is generated by \link{tempfile},
#'   and will be put in the \code{/tmp} folder,
#'   which is cleaned by the operating system
#' @param trans_membrane_analysis_filename Filename for
#'   uhhh, something, for example
#'   `tmh-predictions/trans-membrane-analysis-shortened.txt`
#' @param verbose set to TRUE for more output
#' @author Richel J.C. Bilderbeek
#' @note This is an internal function, so it should be marked with
#'   \code{@noRd}. This is not done, as this will disallow all
#'   functions to find the documentation parameters
default_params_doc <- function(
  alleles,
  binding_strength_threshold,
  epitopeome_filename,
  fasta_filename,
  haplotypes,
  kyte_doolittle_scale_as_data_filename,
  netmhc2pan_filename,
  protein_lengths_filename,
  proteome_filename,
  tmh_9mers_as_data_filename,
  tmh_overlapping_binders_as_data_filename,
  tmhmm_filename,
  trans_membrane_analysis_filename,
  verbose
) {
  # Nothing
}
