# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the auto correlation time
#' from \url{https://github.com/beast-dev/beast-mcmc/blob/800817772033c13061f026226e41128d21fd14f3/src/dr/inference/trace/TraceCorrelation.java#L159} # nolint
#' @param sample sample
#' @param sample_interval sample interval
#' @return the auto correlation time
#' @author Richel J.C. Bilderbeek
create_tmh_fasta_cpp <- function(proteome_filename, tmhs_filename, tmh_fasta_filename) {
    invisible(.Call(`_bbbq_create_tmh_fasta_cpp`, proteome_filename, tmhs_filename, tmh_fasta_filename))
}

