# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates a FASTA fike with only the TMHs
#' @param proteome_filename name of the file the proteome will be stored at
#' @param tmhs_filename file that contains the TMHs as created by TMHMM
#' @param tmh_fasta_filename name of the FASTA file containing only the TMHs
#' @return nothing
#' @author Richel J.C. Bilderbeek
create_tmh_fasta_cpp <- function(proteome_filename, tmhs_filename, tmh_fasta_filename) {
    invisible(.Call(`_bbbq_create_tmh_fasta_cpp`, proteome_filename, tmhs_filename, tmh_fasta_filename))
}

